services:
  letsencrypt:
    image: mwaeckerlin/letsencrypt
    build: .
    environment:
      EMAIL: "me@somewhere.universe"
      DOMAINS: "domain.com,a.domain.com,b.domain.com example.com"
      PREFIXES: "www mail"
      # While testing, point lego at the Let's Encrypt staging server:
      OPTIONS: "--server letsencrypt-staging"
    volumes:
      - type: volume
        source: certificates
        target: /etc/letsencrypt
      - type: volume
        source: acme
        target: /acme

volumes:
  certificates:
  acme:
