version: "3.4"
services:
  certbot:
    image: mwaeckerlin/letsencrypt
    build: .
    environment:
      EMAIL: "me@somewhere.universe"
      DOMAINS: "domain.com,a.domain.com,b.domain.com example.com"
      PREFIXES: "www mail"
      OPTIONS: "--dry-run"
